LUA = ..

include $(LUA)/config

SRCS = \
	lua.h\
	lualib.h\
	lauxlib.h\

all:
	@sleep 0
	
lib:
	@sleep 0

clean:
	@sleep 0

clean_lib:
	@sleep 0

co:
	@co -q -f -M $(SRCS)

klean:	clean
	@rm -f $(SRCS)
